// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDR-K5_BRL-GgcEN0-wjaS3DgiAVRoTZk',
    appId: '1:571257066823:web:2629648370ecf4ae0be862',
    messagingSenderId: '571257066823',
    projectId: 'chat2-72cdb',
    authDomain: 'chat2-72cdb.firebaseapp.com',
    databaseURL: 'https://chat2-72cdb-default-rtdb.firebaseio.com',
    storageBucket: 'chat2-72cdb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAQCQZbfNbE-wFalt29eTTir9Sfuu9NbU',
    appId: '1:571257066823:android:c8bc2ae87d80f5500be862',
    messagingSenderId: '571257066823',
    projectId: 'chat2-72cdb',
    databaseURL: 'https://chat2-72cdb-default-rtdb.firebaseio.com',
    storageBucket: 'chat2-72cdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAQCQZbfNbE-wFalt29eTTir9Sfuu9NbU',
    appId: '1:571257066823:ios:c8bc2ae87d80f5500be862',
    messagingSenderId: '571257066823',
    projectId: 'chat2-72cdb',
    authDomain: 'chat2-72cdb.firebaseapp.com',
    databaseURL: 'https://chat2-72cdb-default-rtdb.firebaseio.com',
    storageBucket: 'chat2-72cdb.firebasestorage.app',
    iosBundleId: 'com.example.chat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAQCQZbfNbE-wFalt29eTTir9Sfuu9NbU',
    appId: '1:571257066823:ios:c8bc2ae87d80f5500be862',
    messagingSenderId: '571257066823',
    projectId: 'chat2-72cdb',
    authDomain: 'chat2-72cdb.firebaseapp.com',
    databaseURL: 'https://chat2-72cdb-default-rtdb.firebaseio.com',
    storageBucket: 'chat2-72cdb.firebasestorage.app',
    iosBundleId: 'com.example.chat2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDR-K5_BRL-GgcEN0-wjaS3DgiAVRoTZk',
    appId: '1:571257066823:web:dcee5db5f2f0825f0be862',
    messagingSenderId: '571257066823',
    projectId: 'chat2-72cdb',
    authDomain: 'chat2-72cdb.firebaseapp.com',
    databaseURL: 'https://chat2-72cdb-default-rtdb.firebaseio.com',
    storageBucket: 'chat2-72cdb.firebasestorage.app',
  );

}